### ISSUE TITLE
Default $params['limit'] isn't set

### ISSUE THREAD

**Issue by Daltonmedia** [arckinteractive/elgg_solr#17]
I experienced this long time ago and solved it by just providing a limit in my query, but now I looked at integrating solr again and noticed I have a lot of:
```
$options['query'] = 'testuser';
$results = elgg_trigger_plugin_hook('search', 'user', $options, array());
```
in my plugins (Ismayil's tokenize autocomplete plugin is an example) where no limit is given and this causes just an empty array, so no result
Solrs default limit should be 10, but this seems not to be working.

What do you advice? I can replace
```
'rows'   => $params['limit'],
```
with
```
'rows'   => $params['limit'] ? $params['limit'] : '100',
```
in all the hooks, but I rather not do this if you consider this a bug.

**Comment by beck24** [comment]
Fixed in version 1.9.1
