### ISSUE TITLE
Does not work when installed with composer

### ISSUE THREAD

**Issue by ewinslow** [arckinteractive/elgg_solr#20]
This line causes problems:

```php
elgg_register_library('Solarium', dirname(__FILE__) . '/vendor/autoload.php');
```

Because /mod/elgg_solr/vendor/autoload.php doesn't exist if I just install this module with composer like so:

```
composer require arckinteractive/elgg_solr
```

My workaround was to include an empty vendor/autoload.php file in the repo, and then your packaging step I guess can bundle the dependencies if need be and overwrite the vendor/autoload.php file with a real one.

**Comment by beck24** [comment]
oh, I see why that would be, that's annoying

I'm just going to commit the vendors with repo, I've started doing that with other repos anyway as it's been easier to manage in git for our projects

**Comment by ewinslow** [comment]
Sounds fine. Interested to see how things shake out with 2.0 supporting
composer explicitly.

**Comment by beck24** [comment]
Fixed in: https://github.com/arckinteractive/elgg_solr/commit/f8f2b41be611289740e6775236be58aef5762045
