### ISSUE TITLE
Help on integrating/debugging solr at elgg

### ISSUE THREAD

**Issue by lcheng61** [arckinteractive/elgg_solr#22]
Hi,

I installed "solr" hoping to increase the scalability of my site. Now I need some help to integrate and/or debug solr search plugin. I followed the steps 

1. downloaded solr 1.9.5

2. installed both solr and vroom and enabled them at elgg

3. I skipped the step of "Configure Solr with the schema.xml included in the root directory of this plugin." I found "schema.xml" in the root directory and I believe not touching this file will not bother

4. Enter and save the connection information on the plugin settings page:

    host: localhost

    port: 8983

    path: /solr/

    core: collection1

5. I did a "reindex from the plugin setting page". It took about 2 hours and see the message of "Message: Reindex complete"

6. Come to my elgg homepage and typed some common word at "search bar", I see 0 results

7. Turn off solr, and type the same common word at "search bar", I see many results like before.

Did I miss anything ? Do I have to restart the whole site ?

Thanks,

**Comment by beck24** [comment]
```I skipped the step of "Configure Solr with the schema.xml included in the root directory of this plugin." I found "schema.xml" in the root directory and I believe not touching this file will not bother```

I believe this is your problem, if solr isn't configured with the correct schema it's not going to work

**Comment by lcheng61** [comment]
Can you please give me procedure or examples how to do this step ? Thanks!

**Comment by beck24** [comment]
You need to replace the schema.xml in your collection1 core config directory (wherever that is, you'll have to find it) with the one provided from this plugin.  Without the correct config it won't be able to store data.

**Comment by lcheng61** [comment]
Hi Beck, Thanks for your reply. However, I couldn't find a directory with name like "collection1". Do I need to install solr separately or elgg_solr is self-contained ?

ubuntu@ip-172-33-1-222:/$ sudo find ./ -type f -name "collection1" -print
ubuntu@ip-172-33-1-222:/$

**Comment by beck24** [comment]
Solr is a separate application, you need to install it on your server

**Comment by lcheng61** [comment]
Hi Matt,

I have installed solr in another server which I can access the admin page
at URL like "http://solr-myapp.rhcloud.com/". Also I have copied
schema.xml. I followed this
https://github.com/LogicalSpark/openshift-solr-quickstart.

The site name is the URL above I think. But I'm wondering what port number
I should use ? I tried "8983", "8080" and "80", none of them works. Please
advise how to use solr from a different server.

Thanks,

**Comment by beck24** [comment]
Use the url of the solr server in the plugin settings, and the whatever port it is configured on - it's 8983 by default but can really be anything depending on the configuration.  Unfortunately I can't really help you because I don't know what your setup is like - this plugin assumes you can provide the correct settings.

**Comment by beck24** [comment]
Closing this as it's not really an issue with the plugin - good luck!

**Comment by lcheng61** [comment]
Hi Matt,

I sent you email offline. I still need help to overcome this solr-elgg challenge. Once we figure out the solution, I'll write it here so other people can benefit.

**Comment by lcheng61** [comment]
Thanks Matt. The problem can be solved if I turn off the SOLR authentication and use port 80. People who deploy SOLR in a separate server must put SOLR server behind the firewall. 

Here the setting that works for me:
Host: my-app.rhcloud.com
Port: 80
Path: /
Core: collection1
Batch size: 200
