### ISSUE TITLE
One of the plugin's vendors is attempting to write under vendor/ dir

### ISSUE THREAD

**Issue by juho-jaakkola** [arckinteractive/elgg_solr#24]
```
Directory vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer
not writable, please chmod to 777" in file
mod/elgg_solr/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer.php (line 272)
```

Seems like a weird behavior to write under `vendor/`. Not sure how to fix, thought.

**Comment by beck24** [comment]
Yeah it writes a local cache file relative to itself, not much I can do about that.  If it's writeable it'll cache properly and not log this error, if it's not writeable this error gets logged and everything still works, it's likely a slight performance hit though (nothing noticable in the projects I've used it on).
