### ISSUE TITLE
Solarium is not a registered library on 2.1

### ISSUE THREAD

**Issue by Daltonmedia** [arckinteractive/elgg_solr#26]
Hey,
I'm having this problem now since I updated the dev install to 2.1.x and I really cannot find what's going on here.
2.1 refuses to register the composer autoload library and nags about solarium not being a registered library.

I was wondering if anyone else encountered this problem.
Rolling back to 2.0.x fixes the issue.
To make sure this isn't because of some plugin or my install, I installed a fresh copy of 2.1 and the same happens. Also there, rolling back to 2.0.x, and no more nagging about the library. 

I cannot find anything in the changelogs of Elgg that could cause this.
Any thoughts?

**Comment by beck24** [comment]
I just did some work updating this, I didn't have this issue and it was working fine on 2.1.

That said it's loading it differently now anyway, so try the new version.

**Comment by Daltonmedia** [comment]
Thanks, this indeed fixes the issue, still wondering what went wrong if it was only in my install that this happened.

**Comment by mrclay** [comment]
https://github.com/Elgg/www.elgg.org/issues/94
