### ISSUE TITLE
Re-add Solarium library

### ISSUE THREAD

**Issue by mrclay** [arckinteractive/elgg_solr#28]
The "Solarium" elgg library was removed: https://github.com/arckinteractive/elgg_solr/commit/0dda851be27e5334de750009c62a4ffc21df7ee8#diff-7f25214d1900985e8ae31ea3d39f2a22L24 leading to https://github.com/Elgg/www.elgg.org/issues/94.

May I suggest:
```php
elgg_register_library('Solarium', __DIR__ . '/lib/deprecated-lib.php');
```
and
```php
// deprecated-lib.php
elgg_log("Do not depend on the library 'Solarium'.", "NOTICE");
```

**Comment by beck24** [comment]
It wasn't removed, it's still there - it's just loading it directly on init
It seems the community for some reason is using a fork of this of Evan's, I don't know why, so it's far behind.  We should use this repo as the source (or packagist) and all should be well.
