### ISSUE TITLE
Reindex entities on metadata delete

### ISSUE THREAD

**Issue by beck24** [arckinteractive/elgg_solr#32]
eg. profile pic removal

Needs:

    elgg_register_event_handler('delete', 'metadata', 'elgg_solr_metadata_update');

**Comment by Wouter0100** [comment]
A good point. When #30 is being merged, there should also be added a hook to reindex the fields.

**Comment by beck24** [comment]
Fixed in https://github.com/arckinteractive/elgg_solr/commit/71b379c68f7cab76bcbfdcd558673580ac8d17f8

@Wouter0100 I also removed the vendor package, Juho convinced me to give composer another shot at not screwing things up at ElggCamp :)

**Comment by Wouter0100** [comment]
Good job, Juho :-)
