### ISSUE TITLE
schema.solr5.xml fails with solr 6.6.0

### ISSUE THREAD

**Issue by topdog08** [arckinteractive/elgg_solr#42]
Got the latest level of Solr when I installed Elgg and get this error trying to use the example schema:

SolrCore Initialization Failures

    mfp: org.apache.solr.common.SolrException:org.apache.solr.common.SolrException: Could not load conf for core mfp: Can't load schema /var/solr/data/mfp/conf/schema.xml: Plugin Initializing failure for [schema.xml] fieldType

**Comment by topdog08** [comment]
The issue is described here:  http://lucene.472066.n3.nabble.com/Upgrading-from-Solr-5-4-0-to-Solr-6-0-0-td4278972.html#a4278994
I believe I have fixed it by changing units to distanceUnits the one place it is used in schema.xml
However, I will do some more testing and update here if I confirm search works with this change.

**Comment by topdog08** [comment]
FWIW I also see this in the logs for the future: TokenFilterFactory is using deprecated 5.2.1 emulation. You should at some point declare and reindex to at least 6.0,&#8203; because 5.x emulation is deprecated and will be removed in 7.0

**Comment by topdog08** [comment]
Looks like this could be a problem too, still no results in some cases with Solr 6.6.0 but 5.5.3 works fine.

https://lucene.apache.org/solr/6_6_0/solr-core/deprecated-list.html

Deprecated Classes Class and Description
org.apache.solr.schema.GeoHashField
use LatLonPointSpatialField instead
org.apache.solr.search.Insanity
org.apache.solr.schema.LatLonType
use LatLonPointSpatialField instead

**Comment by beck24** [comment]
Solr 6 config is provided in the /install directory
